#!/bin/bash
usage() 

max_depth=""
if [ "$1" == "--max_depth" ]; then
    if [ $# -lt 4 ]; then
        usage
    fi
    max_depth="$2"
    input_dir="$3"
    output_dir="$4"
else
    if [ $# -ne 2 ]; then
        usage
    fi
    input_dir="$1"
    output_dir="$2"
fi

if [ ! -d "$input_dir" ]; then
    exit 1
fi

mkdir -p "$output_dir"

fc="find \"$input_dir\" -type f"
if [ -n "$max_depth" ]; then
    fc+=" -maxdepth $max_depth"
fi

eval "$fc" | while read -r file; do
    filename=$(basename "$file")
    de="$output_dir/$filename"
    count=1

    while [ -e "$dest" ]; do
        base="${filename%.*}"
        ext="${filename##*.}"
        if [[ "$base" == "$ext" ]]; then
            ext=""
        else
            ext=".$ext"
        fi
        de="$output_dir/${base}_$count$ext"
        ((count++))
    done
    cp "$file" "$de"
done
