[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = [
<<<<<<< HEAD
    "E",  # pycodestyle
    "F",  # Pyflakes
    "UP",  # pyupgrade
    "B",  # flake8-bugbear
    "SIM",  # flake8-simplify
    "I", # isort
    "ASYNC",
    "C4",  # comprehensions
    "ISC",  # implicit string concat
    "PT",  # pytest
    "RET",  # return
    "PTH",  # pathlib
    "ERA",  # remove commented code
    "PD",  # pandas
    "PGH",  # use specific error code for lint ignores
    "PL",  # pylint
    "NPY",  # numpy
=======
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    "ASYNC",
    # comprehensions
    "C4",
    # implicit string concat
    "ISC",
    # pytest style
    "PT",
    # return
    "RET",
    # use pathlib
    "PTH",
    # remove commented code
    "ERA",
    # pandas-vet
    "PD",
    # use specific error code for type ignores
    "PGH",
    # pylint
    "PL",
    # numpy
    "NPY",
>>>>>>> 3b007e3 (prob1)
    "PERF",
    "FURB",
]
ignore = [
<<<<<<< HEAD
    "E501",  # Line too long
    "PTH123",  # open should be replaced by Path.open
    "ISC001",
    "PLR0913",  # Func argument limit
=======
    # Line too long
    "E501",
    # open should be replaced by Path.open
    "PTH123",
    "ISC001",
>>>>>>> 3b007e3 (prob1)
]

[tool.mypy]
strict = true
<<<<<<< HEAD
disallow_untyped_calls = false
allow_redefinition = true
no_implicit_reexport = false

[project]
name = "hse-tp-git"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AndBoyS", email = "andboyxd@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.3.5",
]

[dependency-groups]
dev = [
    "mypy>=1.14.1",
    "ruff>=0.9.2",
]
=======

[tool.uv]
package = true

[project]
name = "hse-tp-task-test"
version = "0.1.0"
description = ""
authors = [
    { name = "AndBoyS", email = "andboyxd@gmail.com" }
]
readme = "README.md"
requires-python = "~=3.13"
dependencies = [
    "click>=8.1.7",
    "mypy>=1.13.0",
    "natsort>=8.4.0",
    "pytest>=8.3.3",
    "pytest-cov>=6.1.1",
    "ruff>=0.8.0",
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src"]
>>>>>>> 3b007e3 (prob1)
